version: "3.9"

services:
  db:
    image: postgres:16
    container_name: blog-db
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - blog-net
    restart: unless-stopped

  backend:
    image: 211125427196.dkr.ecr.sa-east-1.amazonaws.com/blog-backend:latest
    container_name: blog-backend
    environment:
      PGHOST: db
      PGPORT: ${PGPORT}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      HF_API_KEY: ${HF_API_KEY}
      HF_MODEL: ${HF_MODEL}
      UNSPLASH_ACCESS_KEY: ${UNSPLASH_ACCESS_KEY}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
    depends_on:
      - db
    ports:
      - "4000:4000"
    networks:
      - blog-net
    restart: unless-stopped

  frontend:
    image: 211125427196.dkr.ecr.sa-east-1.amazonaws.com/blog-frontend:latest
    container_name: blog-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - blog-net
    restart: unless-stopped

networks:
  blog-net:

volumes:
  pgdata:
